version: "3.8"
services:
  web:
    container_name: web_app
    image: python
    build: .
    expose:
      - "5000"
    ports:
      - "5000:5000"
    networks:
      - web

  database:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: db
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./tables.sql:/docker-entrypoint-initdb.d/tables.sql
    networks:
      - web
networks:
  web:
    name: web